development:
  adapter: postgresql
  encoding: unicode
  database: todo
  pool: 5
  username: postgres
  password: 'asgard'
  
test:
  adapter: postgresql
  encoding: unicode
  database: todo
  pool: 5
  username: postgres
  password: 'asgard'

production:
  adapter: postgresql
  encoding: unicode
  database: todo
  pool: 5
  username: postgres
  password: 'asgard'